server:
  name: "gm-user"
  port: 8081

zap:
  debugFileName: "/logs/debug/gm-user-debug.log"
  infoFileName:  "/logs/info/gm-user-info.log"
  warnFileName:  "/logs/error/gm-user-error.log"
  maxSize: 500
  maxAge: 28
  maxBackup: 3

redis:
  address:
    - 192.168.254.128:16379
  max_idle: 200
  max_active: 200
  idle_timeout: 240
  username:
  password: 'milowang123'
  cluster: False

